version: '3.2'

services:
  rust:
    build:
      context: .
      dockerfile: ./rust/Dockerfile
    environment:
      - TZ=JST-9
      - USER
    tty: true
    volumes:
      - type: bind
        source: ../
        target: /home/workspace
    networks:
      - rustnet
    ports:
      - 8080:8080

networks:
  rustnet:
    external: true